Friendlist and Friendrequests
SE-TINF22B6/DHBWhub pull request #518
Opened 2024-04-23 18:44 UTC by FurKay00

- Added endpoints, which allows the frontend to receive the friendlist of a user + received/sent friend requests
- Both sent and received friendrequests come as a whole list and can be seperated through the attribute "status"

2024-04-23 19:31 UTC, maxschwinghammer commented on src/main/java/de/tinf22b6/dhbwhub/mapper/FriendshipMapper.java
Code needs to be formatted correctly, some spaces are missing before and after brackets

2024-04-23 19:34 UTC, maxschwinghammer commented on src/main/java/de/tinf22b6/dhbwhub/service/FriendshipServiceImpl.java
Can be simplified with `import java.util.*;`

2024-04-23 19:34 UTC, maxschwinghammer commented on src/main/java/de/tinf22b6/dhbwhub/service/interfaces/FriendshipService.java
Simplification possible

2024-04-23 19:36 UTC, maxschwinghammer requested changes
@FurKay00 Left a few small comments

2024-04-23 20:18 UTC, denniskp approved these changes

2024-04-24 06:26 UTC, Nahlam4 approved these changes
ich mag die formatierung!

2024-04-24 06:39 UTC, denniskp approved these changes
Die Formatierung ist perfekt

2024-04-24 09:10 UTC, merged