Backend for authentification (login/signup)
SE-TINF22B6/DHBWhub pull request #532
Opened 2024-04-25 15:35 UTC by JonasEbbinghaus25

2024-04-25 17:23 UTC, FurKay00 approved these changes

2024-04-25 18:12 UTC, denniskp requested changes

2024-04-25 18:12 UTC, denniskp commented on src/main/java/de/tinf22b6/dhbwhub/config/BasicAuthWebSecurityConfig.java
> -	public InMemoryUserDetailsManager userDetailsService() {
Kannst du diese Bean noch in eine der neuen Klassen verschieben?

2024-04-26 21:13 UTC, denniskp approved these changes

2024-04-27 09:43 UTC, merged