Connect frontend with backend for login + integrate a new profile page
SE-TINF22B6/DHBWhub pull request #564
Opened 2024-05-01 21:50 UTC by JonasEbbinghaus25

2024-05-02 08:12 UTC, maxschwinghammer requested changes
React CI failing. Solved

2024-05-02 13:41 UTC, FurKay00 commented on src/main/java/de/tinf22b6/dhbwhub/controller/AuthController.java
> +        System.out.println("Request:");
Pls delete

2024-05-02 17:09 UTC, JonasEbbinghaus25 commented on src/main/java/de/tinf22b6/dhbwhub/controller/AuthController.java
> +        System.out.println("Request:");
Deleted

2024-05-02 20:00 UTC, maxschwinghammer requested changes
Please adjust the design, you had it better before

2024-05-03 12:11 UTC, FurKay00 approved these changes

2024-05-03 12:41 UTC, maxschwinghammer approved these changes

2024-05-03 12:41 UTC, merged