Implemented Search and user page
SE-TINF22B6/DHBWhub pull request #893
Opened 2024-06-09 20:14 UTC by Nahlam4

Implemented Search and user Page with full funcionality

2024-06-09 20:17 UTC, maxschwinghammer commented on src/main/java/de/tinf22b6/dhbwhub/security/WebSecurityConfig.java
> +            "/post/friend-posts/{id:\\d+}",
`"/post/friend-posts/{id:\\d+}"` should not be public, I just deleted this from this config

2024-06-09 20:18 UTC, maxschwinghammer commented on src/main/java/de/tinf22b6/dhbwhub/security/WebSecurityConfig.java
> +            "/post/friend-posts-by-tag",
`"/post/friend-posts-by-tag"` should not be public, I just deleted this from this config

2024-06-09 20:25 UTC, maxschwinghammer commented on src/main/web/src/scenes/Search/components/Post.tsx
Why do you create a new Post component? Please reuse the existing one.

2024-06-09 20:26 UTC, maxschwinghammer commented on src/main/web/src/scenes/Search/components/PostModel.tsx
Please reuse the existing model

2024-06-09 20:28 UTC, maxschwinghammer commented on src/main/web/src/scenes/Search/components/SearchService.tsx
> +interface UserModel {
Best practise: Extract this to a seperate file called `UserModel` in a folder `models`

2024-06-09 20:32 UTC, maxschwinghammer commented on src/main/web/src/scenes/Search/index.tsx
>          <Footer/>
Please add mobile footer (see other pages for implementation)

2024-06-09 20:33 UTC, maxschwinghammer commented on src/main/web/src/scenes/User/index.tsx
> +                const response: Response = await fetch(`https://localhost:8443/user/user-information/${id}`, {
Do not use localhost, change it to `config.apiUrl`

2024-06-09 20:38 UTC, maxschwinghammer commented on src/main/web/src/atoms/Pictures/Pictures.tsx
Why a random picture instead of the default profile picture?

2024-06-09 20:38 UTC, maxschwinghammer requested changes
Added some comments

2024-06-10 13:18 UTC, maxschwinghammer approved these changes

2024-06-10 13:23 UTC, denniskp approved these changes

2024-06-10 14:01 UTC, merged