Frontend: Added Notifications + Adjustex Notification Endpoints
SE-TINF22B6/DHBWhub pull request #894
Opened 2024-06-09 21:04 UTC by FurKay00

2024-06-09 21:37 UTC, maxschwinghammer commented on src/main/web/package.json
> +    "react": "^18.3.1",
Change this back to version `^18.3.0`

2024-06-09 21:37 UTC, maxschwinghammer commented on src/main/web/package.json
> +    "react-leaflet": "^3.2.5",
Change this back to version `4.2.1`

2024-06-09 21:38 UTC, maxschwinghammer commented on src/main/web/src/organisms/header/Notifications.css
Delete comments

2024-06-09 21:39 UTC, maxschwinghammer commented on src/main/web/src/organisms/header/Notifications.tsx
> +export interface NotificationModel {
Best practise: Extract this to a seperate file called `NotificationModel` in a folder `models`

2024-06-09 21:39 UTC, maxschwinghammer commented on src/main/web/src/organisms/header/Notifications.tsx
> +interface DeleteNotificationModel {
Best practise: Extract this to a seperate file called `DeleteNotificationModel` in a folder `models`

2024-06-09 21:40 UTC, maxschwinghammer commented on src/main/web/src/organisms/login/Login.tsx
> +                navigate("/");
Can then completely removed

2024-06-09 21:40 UTC, maxschwinghammer requested changes
See comments

2024-06-10 07:21 UTC, denniskp approved these changes

2024-06-10 07:28 UTC, Nahlam4 approved these changes

2024-06-10 07:38 UTC, maxschwinghammer approved these changes

2024-06-10 07:38 UTC, merged