Profile page
SE-TINF22B6/DHBWhub pull request #912
Opened 2024-06-10 11:33 UTC by JonasEbbinghaus25

2024-06-10 12:26 UTC, denniskp approved these changes

2024-06-10 13:14 UTC, maxschwinghammer commented on src/main/web/src/scenes/Profile/index.tsx
> +interface UserData {
Best Practise: Extract this to a seperate file called `UserData` in a folder named `models`

2024-06-10 13:17 UTC, maxschwinghammer commented on src/main/web/src/services/ProfileDataService.tsx
> +interface UserData {
Use the model (see comment above)

2024-06-10 13:17 UTC, maxschwinghammer requested changes
Fixed

2024-06-11 09:41 UTC, denniskp approved these changes

2024-06-11 12:39 UTC, FurKay00 approved these changes

2024-06-11 13:07 UTC, maxschwinghammer requested changes
Delete the `change password` or implement it and extract the `UserModel`.
Then you can merge the PR.

2024-06-11 16:37 UTC, Nahlam4 approved these changes

2024-06-11 17:01 UTC, maxschwinghammer approved these changes

2024-06-11 17:01 UTC, merged