Fix sharing from posts on userpage
SE-TINF22B6/DHBWhub pull request #953
Opened 2024-06-12 20:19 UTC by Nahlam4

2024-06-12 21:22 UTC, FurKay00 approved these changes

2024-06-13 06:15 UTC, denniskp requested changes

2024-06-13 06:15 UTC, denniskp commented on src/main/web/src/scenes/User/UserPost.tsx
> +                    <Share postId={id} currentPageURL={"https://www.dhbwhub.de/post/?id="+id}></Share>
Nutze besser `process.env.PUBLIC_URL`

2024-06-13 06:29 UTC, FurKay00 commented on src/main/web/src/scenes/User/UserPost.tsx
> +                    <Share postId={id} currentPageURL={"https://www.dhbwhub.de/post/?id="+id}></Share>
![grafik](https://github.com/SE-TINF22B6/DHBWhub/assets/122597204/58b58ba8-79a9-4361-8fb0-aa18b9940186)

2024-06-13 07:35 UTC, denniskp approved these changes

2024-06-13 07:36 UTC, merged